#-------------------RESTAURANTS----------------------
###get all
GET http://localhost:8080/restaurantvote/restaurants/get
Accept: application/json
Authorization: Basic abc@abc.com user

###

#get
GET http://localhost:8080/restaurantvote/restaurants/100002
Accept: application/json
Authorization: Basic abc1@abc.com admin

###

###delete
DELETE http://localhost:8080/restaurantvote/restaurants/100015
Authorization: Basic abc1@abc.com admin

###

###create
POST http://localhost:8080/restaurantvote/restaurants
Accept: application/json
Content-Type: application/json
Authorization: Basic abc1@abc.com admin

{
  "name": "Кафе-тест"
}

###

###update
PUT http://localhost:8080/restaurantvote/restaurants
Accept: application/json
Content-Type: application/json
Authorization: Basic abc1@abc.com admin

{
  "id": 100015,
  "name": "Кафе-мафе"
}

###

#----------------------VOTES----------------------------------
###get all
GET http://localhost:8080/restaurantvote/votes/
Authorization: Basic abc@abc.com user
Accept: application/json

###

###get all by user
GET http://localhost:8080/restaurantvote/votes/users/
Authorization: Basic abc@abc.com user
Accept: application/json

###

###get all by admin
GET http://localhost:8080/restaurantvote/votes/users/
Authorization: Basic abc1@abc.com admin
Accept: application/json

###

###get all from restaurantId
GET http://localhost:8080/restaurantvote/votes/restaurants/100002
Accept: application/json
Authorization: Basic abc@abc.com user

###

###delete by user by voteId and userId
DELETE http://localhost:8080/restaurantvote/votes/100011
Authorization: Basic abc@abc.com user

###

###create by user for restaurant
POST http://localhost:8080/restaurantvote/votes/restaurants/100002
Authorization: Basic abc@abc.com user
Accept: application/json
Content-Type: application/json

{
  "user": {
    "id": "100000"
  }
}

###

###update by user for restaurant
PUT http://localhost:8080/restaurantvote/votes/restaurants/100004
Authorization: Basic abc@abc.com user
Accept: application/json
Content-Type: application/json

{
  "id": "100011",
  "user": {
    "id": "100000"
  }
}

###update by admin for restaurant
PUT http://localhost:8080/restaurantvote/votes/restaurants/100003
Authorization: Basic abc1@abc.com admin
Accept: application/json
Content-Type: application/json

{
  "id": "100012",
  "user": {
    "id": "100001"
  }
}


###

#---------------------------------------USER-------------------------------
###get all
GET http://localhost:8080/restaurantvote/users/admin
Accept: application/json
Authorization: Basic abc1@abc.com admin

###

###get by id
GET http://localhost:8080/restaurantvote/users/
Accept: application/json
Authorization: Basic abc1@abc.com admin

###

###delete by id
DELETE http://localhost:8080/restaurantvote/users/
Authorization: Basic Krendel@notuse.com 12345

###

###create
POST http://localhost:8080/restaurantvote/users/register
Accept: application/json
Content-Type: application/json

{
  "name": "Вася",
  "email": "Krendel@notuse.com",
  "password": "12345"
}

###

###update
PUT http://localhost:8080/restaurantvote/users
Accept: application/json
Content-Type: application/json
Authorization: Basic Krendel@notuse.com 12345

{
  "id": "100015",
  "name": "Уже не вася",
  "email": "Krendel@notuse.com",
  "password": "12345"
}

###

#---------------------------------------------DISH---------------------------------------

###get by id and restaurantId
GET http://localhost:8080/restaurantvote/dishes/100005/restaurants/100002
Accept: application/json
Authorization: Basic abc1@abc.com admin

###

###get all by restaurantId
GET http://localhost:8080/restaurantvote/dishes/restaurants/100004
Accept: application/json
Authorization: Basic abc1@abc.com admin

###

###delete by id and restaurantId
DELETE http://localhost:8080/restaurantvote/dishes/100005/restaurants/100002
Authorization: Basic abc1@abc.com admin

###

###create
POST http://localhost:8080/restaurantvote/dishes/restaurants/100004
Accept: application/json
Content-Type: application/json
Authorization: Basic abc1@abc.com admin

{
  "price": "220",
  "description": "Гречка"
}

###

###update
PUT http://localhost:8080/restaurantvote/dishes/restaurants/100004
Accept: application/json
Content-Type: application/json
Authorization: Basic abc1@abc.com admin

{
  "id": 100010,
  "price": "220",
  "description": "Гречка"
}

###